### ISSUE TITLE
Illegal character "\\" on windows while generating path for parquet files?

### ISSUE THREAD

**Issue by Eshanatnight** [parseablehq/parseable#650]
![Screenshot 2024-02-06 090110](https://github.com/parseablehq/parseable/assets/60269431/020e2680-4271-4308-a8f4-aeba1743624d)

Some unknow trace error

```
thread '<unnamed>' panicked at server\src\storage\localfs.rs:217:10:
called `Result::unwrap()` on an `Err` value: BadSegment { path: "D:\\dev\\pinit\\data\\teststream/date=2024-02-06/hour=03/minute=28/Loralie.data.parquet", source: InvalidPart { segment: "D:\\dev\\pinit\\data\\teststream", illegal: "\\" } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at server\src\storage\localfs.rs:217:10:
called `Result::unwrap()` on an `Err` value: BadSegment { path: "D:\\dev\\pinit\\data\\teststream/date=2024-02-06/hour=03/minute=28/Loralie.data.parquet", source: InvalidPart { segment: "D:\\dev\\pinit\\data\\teststream", illegal: "\\" } }
thread '<unnamed>' panicked at server\src\storage\localfs.rs:217:10:
called `Result::unwrap()` on an `Err` value: BadSegment { path: "D:\\dev\\pinit\\data\\teststream/date=2024-02-06/hour=03/minute=28/Loralie.data.parquet", source: InvalidPart { segment: "D:\\dev\\pinit\\data\\teststream", illegal: "\\" } }
thread '<unnamed>' panicked at server\src\storage\localfs.rs:217:10:
called `Result::unwrap()` on an `Err` value: BadSegment { path: "D:\\dev\\pinit\\data\\teststream/date=2024-02-06/hour=03/minute=28/Loralie.data.parquet", source: InvalidPart { segment: "D:\\dev\\pinit\\data\\teststream", illegal: "\\" } }
```

**Comment by Delta456** [comment]
I would like to solve this basic issue to learn Rust and get more familiar with the codebase.

**Comment by Eshanatnight** [comment]
@Delta456 Go for it! I'll assign it
