### ISSUE TITLE
Server crashed when querying unknown stream (arrow flight endpoint).

### ISSUE THREAD

**Issue by balaji-jr** [parseablehq/parseable#821]
Stacktrace:
[2024-06-14T14:59:28Z ERROR actix_http::h1::dispatcher] stream error: request parse error: invalid Header provided                                                                                                 
[2024-06-16T06:31:51Z ERROR actix_http::h1::dispatcher] stream error: request parse error: invalid Header provided                                                                                                 
[2024-06-17T01:03:27Z ERROR actix_http::h1::dispatcher] stream error: request parse error: invalid Header provided                                                                                                 
[2024-06-17T06:02:36Z ERROR actix_http::h1::dispatcher] stream error: request parse error: invalid Header provided                                                                                                 
[2024-06-17T10:08:36Z ERROR parseable::handlers::airplane] Datafusion Error: Failed to create logical plan: Error during planning: table 'datafusion.public.webapp' not found                                      
[2024-06-17T10:09:47Z ERROR parseable::handlers::airplane] Datafusion Error: Failed to create logical plan: Error during planning: table 'datafusion.public.webapp' not found                                      
thread 'main' panicked at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-array-51.0.0/src/record_batch.rs:376:9:                                                                          
assertion failed: (offset + length) <= self.num_rows()                                                                                                                                                             
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                                                                                                                      
thread 'local-sync' panicked at server/src/event/writer.rs:215:46:                                                                                                                                                 
called `Result::unwrap()` on an `Err` value: PoisonError { .. }                                                                                                                                                    
Error: Failed to sync local data to drive. Please restart the Parseable server.

**Comment by dharanad** [comment]
@nitisht how to reproduce the issue. Can you please share some info

**Comment by nitisht** [comment]
cc @balaji-jr

**Comment by balaji-jr** [comment]
Closing this issue as it is not reproducible now. 
@nitisht @dharanad
